CHANGELOG.rst, docs/api.rst, docs/usage.ipynb, primap2/_metadata.py, primap2/accessors.py, primap2/tests/conftest.py, primap2/tests/test_metadata.py
Access metadata easily via properties like `ds.pr.references`. This helps because properties are typed and guard against
typos. Also, they are documented using docstrings and therefore available in on-line help.
=> Access metadata easily via properties.

requirements_dev.txt, setup.py
h5py was pinned due to API changes in Version 3, but this was fixed in xarray at https://github.com/pydata/xarray/pull/4893 , so we can now unpin h5py but have to use a newer h5netcdf.
=> Unpin h5py and require fixed h5netcdf version.

Makefile
=> Unconditionally remove generated folder before building docs.

changelog_unreleased/doc-fixes.rst, docs/requirements.txt
readthedocs builds are currently failing, and I try to find out why.
=> Fix building of docs at RTD

changelog_unreleased/new-xarray-compat.rst, primap2/_setters.py, primap2/pm2io/_interchange_format.py
The latest (not-yet-released) version of xarray contains a [rework of indexing](https://github.com/pydata/xarray/pull/5692) and some small changes to our I/O functions are necessary to support both old and new xarray.
=> Replace hacks that worked on old versions of xarray with proper xarray calls

.github/workflows/ci.yml, .readthedocs.yml, changelog_unreleased/fix-gas-basket-functions.rst, changelog_unreleased/python.3.10.rst, docs/requirements.txt, primap-stubs.patch, primap2/_aggregate.py, primap2/tests/test_aggregate.py, setup.cfg, tox.ini
* Change behaviour of gas basket aggregation functions to be the same as
other aggregation functions.
Now, `ds.pr.gas_basket_contents_sum()` and
`ds.pr.fill_na_gas_basket_from_contents()` work like `ds.pr.sum()`.
Both now have a `skipna` argument, and operate as if `skipna=True`
by default.
Note that this is a breaking change, by default NaNs are now
treated as zero values when aggregating gas baskets!
* Drop python 3.7 support and add python 3.10 support following NEP 29.
=> Fix gas basket functions + python 3.10

.github/workflows/ci.yml, .pre-commit-config.yaml, changelog_unreleased/drop_python_3.8.rst, docs/conf.py, docs/development.rst, setup.cfg, tox.ini
Drop support for python 3.8. It is due to be dropped by numpy on April 14 (see [NEP 29 support table](https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table)) and we see CI failures already.
=> Drop python 3.8

.github/workflows/ci.yml, changelog_unreleased/no-python39.rst, docs/development.rst, primap2/_aggregate.py, primap2/_alias_selection.py, primap2/_data_format.py, primap2/_downscale.py, primap2/_merge.py, primap2/_overview.py, primap2/_setters.py, primap2/_units.py, primap2/pm2io/_GHG_inventory_reading.py, primap2/pm2io/_data_reading.py, primap2/pm2io/_interchange_format.py, pyproject.toml, setup.cfg, tox.ini
Numpy will stop supporting Python 3.9 on April 5th, so let's stop writing code for Python 3.9 now.
=> Remove python 3.9 support

.check_python_version.py, changelog_unreleased/no-python312.rst, setup.cfg
Specify minimal and maximal python versions in our python version dependencies.
I guess the `.check_python_version.py` script is not necessary any more (pip rejects this by itself using the configuration in `setup.cfg`), but it has the advantage that it is run in Makefile before anything else when setting up a development environment, so it provides a fast feedback and readable error message. So, I just left it in.
Closes: #206
=> Tighten dependencies on python versions

changelog_unreleased/compose-entity.rst, primap2/csg/_compose.py, primap2/csg/_models.py, primap2/tests/csg/test_compose.py, setup.cfg
* general cleaning up of `compose`
* strategy and priority selectors:
- support and test multiple values per dimension (priority: not for priority dimensions)
- support selecting by entity (not for priority dimensions)
=> Compose: Use entities in priority and strategy selectors, refactor

primap2/_units.py
monkey-patch the changes from https://github.com/hgrecco/pint/pull/1959 into pint so that performance goes back to normal
=> ugly: add a hack to monkey-patch pint's ndim for speed

primap2/tests/csg/test_compose.py
Use public API paths instead of private API paths where they exist in the CSG tests.
=> clean up CSG tests

primap2/csg/_compose.py, primap2/csg/_models.py, primap2/tests/csg/test_compose.py, primap2/tests/csg/test_models.py, primap2/tests/csg/utils.py
* `entity` and `variable` are defined things in primap2, actually use the terms correctly in the code and interfaces.
* Allow filtering by `entity` and `variable` in strategy and priority definitions.
* Better error messages if undefined dimensions are used in strategy definitions.
=> Properly use variables and entities in definitions and skipping

changelog_unreleased/fix-if-dimensionless.rst, primap2/pm2io/_interchange_format.py
Some library update (pandas or xarray, likely) broke parsing of dimensionless units from the interchange format due to NaN issues. This fixes it.
=> fix: interchange format works again with dimensionless units

Makefile, changelog_unreleased/xarray_coordinate_bug_workaround.md, primap2/_aggregate.py, primap2/_downscale.py, primap2/_fill_combine.py, primap2/_merge.py, primap2/accessors.py, primap2/tests/test_fill_combine.py, primap2/tests/test_merge.py
This pr adds a workaround for the issue with additional (non-indexed) coordinates in some xarray functions (https://github.com/pydata/xarray/issues/9124). 
There are also some small improvements of error messages included. 
The workaround is to add custom `pr.fillna` and `pr.combine_first` methods which wrap around `fillna` and `combine_first` and take care of the additional coordinate. 
The improvements to error messages are to give more relevant information on the data that caused the error.
=> workaround for xarray additional coordinate bug

changelog/271.docs.md, changelog/274.docs.md, docs/source/usage/store_and_load.md
Add a paragraph to the docs which warns that netcdf files are not reproducible.
Closes: #184
=> docs: add warning about non-reproducible netcdf files

changelog/279.enhancement.md, docs/source/usage/index.md, docs/source/usage/logging.md, docs/source/usage/select_and_view.md, primap2/__init__.py, primap2/tests/conftest.py
* Add documentation about the logging
* Configure the default logger to skip debug messages
=> feat: configure logger to skip debug messages by default

primap2/_convert.py, primap2/tests/test_convert.py
Previously the `convert` function supported extensive data (like total emissions in a year subdivided into multiple
sectoral categories) and intensive data (like average per-person emissions in a year subdivided into different territorial entities). We decided that we don't want to support the handling of intensive data, as we don't 
expect this to be a common use case.
This pull request removes the `sum_rule` argument and code and always assumes extensive data. It adds documentation that this is only meant to be used with extensive quantities.
The general plan (Mika): In a first PR remove the `sum_rule`, in a second PR which builds on the first remove the `input_weights` and `output_weights` and raise errors instead if …
=> remove sum rule from conversion

primap2/_convert.py, primap2/tests/test_convert.py
This pull request builds on #281 which should be merged first. Removes the `input_weights` and `output_weights` from the convert function and raise errors if downscaling would be necessary. 
At this point only one-to-one, and many-to-one conversions are possible.
In #284 support for one-to-many conversions is added again.
=> remove input and output weights from convert function

primap2/_convert.py, primap2/tests/data/BURDI_conversion.csv, primap2/tests/data/simple_categorisation_b.yaml, primap2/tests/data/test_create_category_name_conversion.csv, primap2/tests/test_convert.py
Functionality added in this pull request:
- **one-to-many conversion**: Input and output weights are not supported anymore (see PR #282). That means a category (or a group of categories) cannot be split into a group of categories, e.g. `4.B.10 + 4.B.11 + 4.B.12 + 4.B.13 -> 3.A.2.j` works, but `2.C.5 -> 2.C.5 + 2.C.6 + 2.C.7` does not work. When there are several categories on the target side, we now create a new category, e.g. the rule `2.C.5 -> 2.C.5 + 2.C.6 + 2.C.7` would yield a new category `M_2.C.5_2.C.6_2.C.7`. 
- **one-to-one conversion but target category is not part of target categorisation**: If a category on the target side does not exist it we need to create it in the respective categorisation in climate categories. …
=> one-to-many conversion

changelog/278.fix.md, primap2/_downscale.py, primap2/tests/test_downscale.py
Fix issues with 0 data in downscaling functions
=> Fix downscaling functionality

docs/source/api/index.rst, docs/source/data_reading/test_csv_data_sec_cat_if.yaml, docs/source/usage/csg.md, primap2/csg/_strategies/gaps.py, primap2/csg/_strategies/local_trends.py, primap2/csg/_wrapper.py, primap2/tests/csg/test_gaps.py
@JGuetschow it was easier for me to add my refactorings as patches instead of doing them inline in github, so I created a PR into your branch with what I would change in your branch before merging. Changes:
* regenerated api docs (happens if you run "make docs" locally")
* added LocalTrendsStrategy to CSG usage docs
* added some docstrings, moved method docstrings from the class's docstring to the method's docstring
* unified calculate_right_boundary_trend and calculate_left_boundary_trend into one function with case distinctions
* refactored get_shifted_time_value. I first did it with python lists, which is a bit simpler, but using the underlying numpy arrays without converting is much faster, so I did that in the end.
* corrected typos wherever I found them.
=> slight refactorings, docs, typos

changelog/313.fix.md, docs/requirements.txt, primap2/_convert.py, primap2/tests/test_convert.py
Johannes found a bug in the convert function. All nan values were converted to zero. With these changes all nan are still nan after the conversion.
=>  Ensure NaN values remain NaN during conversion

changelog/324.fix.md, primap2/_data_format.py, primap2/_merge.py, primap2/tests/test_data_format.py, primap2/tests/test_merge.py
Fix the truncation problem when saving to netcdf5 after merging.
Closes: #325 
Add a default compression algorithm level and compression level if nothing is specified.
=>  Fix the truncation problem when saving to netcdf5 after merging

docs/source/data_structures.md, docs/source/ideas_for_sparse_data.md, docs/source/index.md
Add the notes on data structure research so they don't get lost
=> Add notes about data structures to documentation
