primap-community/primap2

.github/workflows/ci.yml
CHANGELOG.rst
primap2/_data_format.py
primap2/_setters.py
setup.py

Xarray brings some minor API changes which need some fixes in tests and in open_dataset.
Closes: #20

Fixes for xarray 0.17

---

CHANGELOG.rst
docs/api.rst
docs/usage.ipynb
primap2/_aggregate.py
primap2/_alias_selection.py
primap2/_data_format.py
primap2/_downscale.py
primap2/_overview.py
primap2/_setters.py
primap2/_types.py
primap2/accessors.py
primap2/tests/conftest.py
primap2/tests/test_aggregate.py
primap2/tests/test_alias_selection.py
primap2/tests/test_overview.py
primap2/tests/test_setters.py
setup.cfg

Add a function `pr.coverage` for Datasets and arrays with the functionality of pyCPA's `tools.dataAnalysis.check_coverage`. Closes: #7

pr.coverage function

---

docs/data_reading.rst
docs/datalad.rst
docs/index.rst
setup.cfg

Add minimal datalad documentation with pointers to the official datalad docs.

Datalad docs

---

.github/workflows/ci.yml
.pre-commit-config.yaml
primap2/pm2io/_data_reading.py
primap2/pm2io/_interchange_format.py
update_changelog.py
update_citation_info.py

Using `pyupgrade`, some more good practice stuff can be applied automatically. It is about things which black doesn't catch (like using read mode on file opening explicitly, which is unnecessary, and other harmless but slightly annoying habits of mine).

Add pyupgrade to pre-commit config for more standardization

---

.pre-commit-config.yaml
changelog_unreleased/deprecations.rst
primap2/pm2io/_interchange_format.py

Fix deprecation warning from numpy

fix numpy deprecation warning.

---

changelog_unreleased/ruamel-yaml-pin.rst
setup.cfg

Pin ruamel.yaml to version 0.17.4 until https://github.com/crdoconnor/strictyaml/issues/145 is solved.

Pin ruamel.yaml version.

---

.github/workflows/ci.yml
Makefile
changelog_unreleased/venv-improvements.rst

- [*] Description in a ``.rst`` file in the directory ``changelog_unreleased`` added - remember to include a ``*`` to make it a bullet point
Improve `venv` handling in the Makefile.

Better venv handling.

---

setup.cfg

ruamel.yaml and/or strictyaml were fixed so that things now work again with the latest versions.

Unpin ruamel.yaml after it was fixed.

---

changelog_unreleased/doc-fixes.rst
docs/requirements.txt
setup.cfg

pin sphinx version to repair RTD latex builds

Pin sphinx version to repair RTD latex builds

---

changelog_unreleased/new-openscm-units.rst
setup.cfg

Just require the latest version of openscm-units so that we can rely on its features.

New openscm units

---

primap2/_units.py

Change quantify() wrapper for changed pint-xarray API.

Change quantify() wrapper for changed pint-xarray API.

---

.gitignore
docs/development.rst
tbump.toml
update_changelog.py

Automatically make a github release from tbump, so that less clicking in the github webpage is required for a release.

Automatically make a github release from tbump.

---

changelog_unreleased/compatibility-new-pint-xarray.rst

Forgot the changelog in the earlier PR.

Add changelog entry with details about the pint-xarray fix.

---

changelog_unreleased/faster-merge.rst
primap2/_merge.py

Use xarray's `DataArray.combine_first` function to do the heavy lifting in `pr.merge` instead of our own recursive algorithm. This is at least 10x faster than the previous algorithm for our tests, and easier to understand.

Faster merge

---

.gitignore
.pre-commit-config.yaml
.readthedocs.yml
AUTHORS.rst
README.rst
changelog_unreleased/depend-openscm-units.rst
changelog_unreleased/no-pdf-docs.rst
primap2/_aggregate.py
primap2/_alias_selection.py
primap2/_data_format.py
primap2/_downscale.py
primap2/_merge.py
primap2/_overview.py
primap2/_setters.py
primap2/_units.py
primap2/pm2io/_GHG_inventory_reading.py
primap2/pm2io/_data_reading.py
primap2/pm2io/_interchange_format.py
primap2/tests/test_data_reading.py
primap2/tests/test_setters.py
primap2/tests/utils.py
pyproject.toml
setup.cfg

* Depend on openscm-units >= 0.5.1 to make sure #150 doesn't bite us again.
* Stop building pdf documentation. It doesn't support SVG images and nobody uses it anyway.

Small fixes

---

.pre-commit-config.yaml
changelog_unreleased/fix-new-pint.rst
primap2/tests/test_aggregate.py

Fix tests with new pint version. Also incorporates https://github.com/pik-primap/primap2/pull/152

Fix tests with new pint version

---

.check_python_version.py
Makefile

Check the python version before creating or updating the development virtual environment

Enforce python minimum version when creating or updating virtual environment

---

.readthedocs.yml
changelog_unreleased/fix-rtd.rst

Fix build failures on readthedocs due to https://blog.readthedocs.com/drop-support-system-packages/

docs: newer RTD configuration

---

docs/development.rst

Small doc fixes

---

changelog_unreleased/new-pint.rst
docs/usage.ipynb
primap2/tests/test_downscale.py
primap2/tests/test_overview.py
primap2/tests/test_setters.py
setup.cfg

fix: works for latest pint

---

.github/workflows/ci.yml
.pre-commit-config.yaml
changelog_unreleased/no-python39.rst
changelog_unreleased/ruff-format.rst
docs/development.rst
primap2/_aggregate.py
primap2/_alias_selection.py
primap2/_data_format.py
primap2/_downscale.py
primap2/_merge.py
primap2/_overview.py
primap2/_setters.py
primap2/_units.py
primap2/pm2io/_GHG_inventory_reading.py
primap2/pm2io/_data_reading.py
primap2/pm2io/_interchange_format.py
primap2/tests/test_data_reading.py
primap2/tests/test_downscale.py
primap2/tests/test_setters.py
pyproject.toml
setup.cfg
tox.ini

Use ruff format instead of black

Ruff formatting instead of black

---

primap2/tests/csg/test_compose.py

With a bit of thinking, I was able to add a bit more complexity to our "trivial" test of `compose` so that it actually uses strategy definitions and therefore would have detected the entity bug fixed in #213 .
I also renamed the "trivial" test to a "simple" test because it isn't so trivial anymore :wink:

test: catch entity bug in integration test

---

docs/development.rst
primap-stubs.patch

Newer versions of xarray need new stubs patches again.

fix: make stubs patch apply again.

---

setup.cfg

I forgot to actually add the CSG sub-modules into the `setup.cfg` `options.packages` option, as noticed by @JGuetschow . This fixes it.

fix: actually install CSG sub-modules in the package

---

primap2/csg/_models.py
primap2/tests/csg/test_compose.py
primap2/tests/csg/test_models.py

Fix match selector for selections with lists of entities and add tests for that
No RST file as just a small fix to unreleased code

* fix match_selector for multiple entities and add tests

---

primap2/_aggregate.py
primap2/_data_format.py
primap2/tests/test_aggregate.py

`gas_basket_contents_sum` now deals with new baskets, which simplifies `aggregate_entities`.

add new basket in gas_basket_contents_sum

---

primap2/_merge.py

Just a tiny bugfix in an error message
Fix a bug in a merge error message

Aggregation fixes

---

primap2/_aggregate.py
primap2/_data_format.py
primap2/_dim_names.py
primap2/csg/_models.py
primap2/tests/examples.py
primap2/tests/test_data_format.py
pyproject.toml

Solve all warnings in a current `make test` run.

fix: solve warnings

---

primap2/_merge.py
primap2/_setters.py
primap2/_units.py
primap2/tests/test_merge.py
primap2/tests/test_selection.py
primap2/tests/test_setters.py

Added tests (and, where needed, fixes) for:
* properly handle time dimension in `pr.set`
* properly format yearly as well as daily data in `pr.merge` error messages

test: add more testing, some fixes

---

changelog/270.trivial.md
docs/source/data_reading/test_csv_data_sec_cat_if.yaml

fix an interchnage format yaml file in docs (field now sorted)

---

changelog/271.docs.md
docs/source/usage/skipna.md

Reintegrate and fix docs for aggregation functions

---

changelog/272.breaking.md
docs/source/usage/skipna.md
primap2/_aggregate.py
primap2/tests/test_aggregate.py

Harmonize filtering / selection parameter names

---

primap2/pm2io/_GHG_inventory_reading.py

let nir_convert_df_to_long retain NaN values

---

.github/workflows/ci-upstream-dev.yml
.github/workflows/ci.yml
changelog/275.trivial.md
docs/source/development.md
setup.cfg

* add a dependency group which installs development versions of central upstream libraries
* add a github actions workflow which tests using the development dependency group
* update versions of gha actions, also upload test results to codecov

Test development versions of upstream libraries

---

changelog/273.fix.md
changelog/276.improvement.md
primap2/_merge.py
primap2/tests/test_merge.py

Add on log content and format for the `pr.merge()` function
also: Add changelog note for pr #273

Add tests for merge function logging

---

changelog/pr.fix.md
primap2/_setters.py
primap2/tests/test_setters.py

Fix set truncation bug

---

Makefile
changelog/322.fix.md
primap2/csg/_strategies/global_least_squares.py
primap2/csg/_strategies/substitution.py
primap2/tests/csg/test_strategies.py

Deals with https://github.com/primap-community/primap2/issues/320

Replace `xarray.core.ops` which is not part of the public xarray API

---

docs/source/api/index.rst
docs/source/data_reading/test_csv_data_sec_cat_if.yaml
primap2/csg/_wrapper.py

a few more typos in API docs and small stylistic fixes

CSG wrapper: small fixes

---

changelog/323.fix.md
changelog/323.improvement.md
docs/source/data_reading/index.md
primap2/pm2io/_GHG_inventory_reading.py
primap2/pm2io/_data_reading.py

* Some small fixes to the handling of flags (NE, NO, FX, ...) in data reading 
* fix in convert an treatment
* fix for pandas stack function in GHG_inventory_reading

Crt reading fixes
